Ok we have the urls. Now let's clone them.

I'm obviously a big fan of using libraries to get things done quickly. Here's another Python library but this time for the git protocol: https://github.com/gitpython-developers/GitPython

Thanks to this stackoverflow comment we have our code https://stackoverflow.com/a/15388550

```python
from git import Repo

Repo.clone_from(git_url, repo_dir)
```

Here is the code I came up with

```py
import os
from git import Repo

for lang in ('Java', 'Python', 'C++'):
	os.makedirs(f'repos/{lang}', exist_ok=True)
	with open(f'repo_urls/{lang}.txt', 'r') as f:
		for i, url in enumerate(f.readlines()):
			url = url.strip()
			name = '_'.join(url.split('/')[-2:]).replace('.git', '') # convert url to folder name
			Repo.clone_from(url, f'repos/{lang}/{name}', depth=1)

			if i % 20 == 0:
				print(f'{lang} repo #{i+1}: {url}')
```

Note the fact that I made `depth=1`. Since we are not doing any time-based stuff, a shallow copy of the repo should be just fine.

![[Pasted image 20240826221346.png]]

Good old java. I already have my file path limit disabled on windows.

As it turns out, Git has its own max file path that can be disabled using `git config --system core.longpaths true`.

Now we are good. Just checked before running the script and I have 106 GB. My fingers are crossed. Let's let it rip.
![[Pasted image 20240826222444.png]]

It seems to have failed on one repo. Let's just modify the code to skip over repos that have already been cloned and run again.

```diff
-			Repo.clone_from(url, f'repos/{lang}/{name}', depth=1)
+			folder = f'repos/{lang}/{name}'
+			if not os.path.exists(folder):
+				Repo.clone_from(url, folder, depth=1)

```
![[Pasted image 20240826222912.png]]

I did not expect that to happen. PC has been restarted and we keep on chugging.

1 hour later and we have this behemoth of a folder

![[Pasted image 20240827201047.png]]

